// paymentPlanEvents.js
// Event definitions and creators for payment plan automation

export const PAYMENT_PLAN_CREATED = 'PaymentPlanCreated';
export const PAYMENT_PLAN_AUTO_GENERATED = 'PaymentPlanAutoGenerated';


export function createPaymentPlanCreatedEvent({ changeId, planDeCalculId, paymentPlanId, decisionId, payments }) {
  return {
    event: PAYMENT_PLAN_CREATED,
    changeId,
    planDeCalculId,
    paymentPlanId,
    decisionId,
    payments, // Array of { month, amount }
  timestamp: new Date().toISOString(),
  };
}

export function createPaymentPlanAutoGeneratedEvent({ changeId, planDeCalculId, paymentPlanId, decisionId, payments }) {
  return {
    event: PAYMENT_PLAN_AUTO_GENERATED,
    changeId,
    planDeCalculId,
    paymentPlanId,
    decisionId,
    payments, // Array of { month, amount }
  timestamp: new Date().toISOString(),
  };
}
