// paymentPlanAutomation.js
// Pure automation function for payment plan creation
import { hasPaymentPlan } from './paymentPlanProjection';
import { createPaymentPlanAutoGeneratedEvent } from './paymentPlanEvents';

/**
 * Automation function: checks if a payment plan should be created and returns new events if needed.
 * - eventLog: array of workflow events
 * Returns: array of new events to append (or empty array)
 */

export function automatePaymentPlanCreation(eventLog) {
  // Find all validated decisions (step 6)
  const validatedDecisions = eventLog.filter(e => e.event === 'DecisionValidee');
  const newEvents = [];

  for (const validatedDecision of validatedDecisions) {
    // Always create a new payment plan for each DecisionValidee
    // Check if a payment plan already exists for this decisionId (not just changeId)
    const alreadyExists = eventLog.some(e =>
      (e.event === 'PaymentPlanCreated' || e.event === 'PaymentPlanAutoGenerated') &&
      e.decisionId === validatedDecision.decisionId
    );
    if (alreadyExists) continue;

    // Use payments from DecisionValidee payload if available, else fallback to deltaPerMonth

    // Always use payments from DecisionValidee payload.payments if present and non-empty
    let payments = [];
    if (
      validatedDecision.payload &&
      Array.isArray(validatedDecision.payload.payments) &&
      validatedDecision.payload.payments.length > 0
    ) {
      payments = validatedDecision.payload.payments.map(p => ({ month: p.month, amount: p.amount }));
    } else if (validatedDecision.payload && validatedDecision.payload.deltaPerMonth) {
      payments = Object.entries(validatedDecision.payload.deltaPerMonth).map(([month, amount]) => ({ month, amount }));
    }

    // Create auto-generated payment plan event, include decisionId
    const paymentPlanEvent = createPaymentPlanAutoGeneratedEvent({
      changeId: validatedDecision.changeId,
      planDeCalculId: validatedDecision.planDeCalculId,
      paymentPlanId: validatedDecision.paymentPlanId,
      decisionId: validatedDecision.decisionId,
      payments,
    });

    // Also open step 7 in the workflow
    const workflowId = validatedDecision.workflowId;
    const stepOpenedEvent = {
      event: 'StepOpened',
      workflowId,
      step: 7,
      ts: new Date().toISOString(),
    };

    newEvents.push(paymentPlanEvent, stepOpenedEvent);
  }

  return newEvents;
}
