// paymentPlanAutomation.js
// Pure automation function for payment plan creation
import { hasPaymentPlan } from './paymentPlanProjection';
import { createPaymentPlanAutoGeneratedEvent } from './paymentPlanEvents';

/**
 * Automation function: checks if a payment plan should be created and returns new events if needed.
 * - eventLog: array of workflow events
 * Returns: array of new events to append (or empty array)
 */
export function automatePaymentPlanCreation(eventLog) {
  // Find latest validated decision (step 6)
  const validatedDecision = eventLog
    .filter(e => e.event === 'DecisionValidee')
    .slice(-1)[0];
  if (!validatedDecision) return [];

  // Only create payment plan if not already present
  if (hasPaymentPlan(eventLog, validatedDecision.changeId)) return [];

  // Use deltaPerMonth from validatedDecision.payload
  const payments = Object.entries((validatedDecision.payload && validatedDecision.payload.deltaPerMonth) || {}).map(([month, amount]) => ({ month, amount }));

  // Create auto-generated payment plan event
  const event = createPaymentPlanAutoGeneratedEvent({
    changeId: validatedDecision.changeId,
    planDeCalculId: validatedDecision.planDeCalculId,
    paymentPlanId: validatedDecision.paymentPlanId,
    payments,
  });
  return [event];
}
