// paymentPlanProjection.js
// Pure projection functions for payment plan state
import { PAYMENT_PLAN_CREATED, PAYMENT_PLAN_AUTO_GENERATED } from './paymentPlanEvents';

/**
 * Computes the current payment plan state from the event log.
 * Returns: {
 *   paymentPlanId,
 *   changeId,
 *   planDeCalculId,
 *   payments: Array<{ month, amount }>,
 *   isAutoGenerated: boolean
 * }
 */
export function getPaymentPlanState(eventLog) {
  let paymentPlan = null;
  for (const event of eventLog) {
    if (event.event === PAYMENT_PLAN_CREATED || event.event === PAYMENT_PLAN_AUTO_GENERATED) {
      paymentPlan = {
        paymentPlanId: event.paymentPlanId,
        changeId: event.changeId,
        planDeCalculId: event.planDeCalculId,
        payments: event.payments || [],
        isAutoGenerated: event.event === PAYMENT_PLAN_AUTO_GENERATED,
      };
    }
  }
  return paymentPlan;
}

/**
 * Returns true if a payment plan exists for the given changeId.
 */
export function hasPaymentPlan(eventLog, changeId) {
  return eventLog.some(e =>
    (e.event === PAYMENT_PLAN_CREATED || e.event === PAYMENT_PLAN_AUTO_GENERATED) &&
    e.changeId === changeId
  );
}
