
// PaymentPlanPage.js
// Displays the current payment plan using event-sourced projections
import React, { useState } from 'react';
import '../layout.css';
import { readWorkflowEventLog } from '../workflowEventLog';
import { getPaymentPlanState } from './paymentPlanProjection';
import EventStream from '../components/EventStream';

export default function PaymentPlanPage() {
  const eventLog = readWorkflowEventLog();
  const paymentPlanProjection = getPaymentPlanState(eventLog);
  const paymentPlan = paymentPlanProjection;
  const [paidMonths, setPaidMonths] = useState([]);
  const [showProjection, setShowProjection] = useState(false);

  // Helper: get last day of month
  function getLastDayOfMonth(monthStr) {
    const [yyyy, mm] = monthStr.split('-').map(Number);
    return new Date(yyyy, mm, 0); // day 0 of next month = last day of month
  }

  // Handler for payment
  function handlePay(month, amount) {
    // Here you would append a PaiementEffectué event
    setPaidMonths([...paidMonths, month]);
    // TODO: appendWorkflowEvents({ event: 'PaiementEffectué', month, amount, ts: new Date().toISOString() })
  }

  const today = new Date();




  // EventStream filter: only PaymentPlanAutoGenerated events for this plan
  const eventStreamFilter = e =>
    e.event === 'PaymentPlanAutoGenerated' &&
    (e.changeId === paymentPlan.changeId || e.planDeCalculId === paymentPlan.planDeCalculId);

  if (!paymentPlan) {
    return (
      <div>No payment plan available.</div>
    );
  }

  return (
    <>
      <div className="event-stream-section">
        <h2>Payment Plan</h2>
        <div style={{ marginBottom: 18 }}>
          <strong>Change ID:</strong> {paymentPlan.changeId}<br />
          <strong>Plan de Calcul ID:</strong> {paymentPlan.planDeCalculId}<br />
          <strong>Payment Plan ID:</strong> {paymentPlan.paymentPlanId}<br />
          <strong>Type:</strong> {paymentPlan.isAutoGenerated ? 'Auto-generated (created by automation)' : 'Manual (created by user)'}
        </div>
        <button
          style={{ float: 'right', marginBottom: 16, padding: '8px 18px', borderRadius: 6, background: '#43a047', color: '#fff', border: 'none', fontWeight: 600, cursor: 'pointer' }}
          onClick={() => setShowProjection(s => !s)}
        >
          {showProjection ? 'Masquer Projection' : 'Afficher Projection'}
        </button>
        {showProjection && (
          <pre style={{ background: '#222', color: '#fff', padding: 16, borderRadius: 8, fontSize: 13, marginBottom: 18 }}>
            {JSON.stringify(paymentPlanProjection, null, 2)}
          </pre>
        )}

        <table className="workflow-table" style={{ marginTop: '1rem' }}>
          <thead>
            <tr>
              <th>Month</th>
              <th>Amount</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            {paymentPlan.payments.map(({ month, amount }) => {
              const lastDay = getLastDayOfMonth(month);
              const canPay = today >= lastDay && !paidMonths.includes(month);
              return (
                <tr key={month}>
                  <td>{month}</td>
                  <td>{amount}</td>
                  <td>
                    {canPay ? (
                      <button onClick={() => handlePay(month, amount)} style={{ padding: '6px 18px', borderRadius: 6, background: '#1976d2', color: '#fff', border: 'none', fontWeight: 600, cursor: 'pointer' }}>Payer</button>
                    ) : paidMonths.includes(month) ? (
                      <span style={{ color: '#388e3c', fontWeight: 600 }}>Payé</span>
                    ) : (
                      <span style={{ color: '#888' }}>En attente</span>
                    )}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
      {/* EventStream outside the main container */}
      <EventStream
        events={eventLog}
        filter={eventStreamFilter}
        maxHeight={400}
        showTitle={true}
      />
    </>
  );
}
