// PaymentPlanPage.js
// Displays the current payment plan using event-sourced projections
import React from 'react';
import { readWorkflowEventLog } from '../workflowEventLog';
import { getPaymentPlanState } from './paymentPlanProjection';

export default function PaymentPlanPage() {
  const eventLog = readWorkflowEventLog();
  const paymentPlan = getPaymentPlanState(eventLog);

  if (!paymentPlan) {
    return <div>No payment plan available.</div>;
  }

  return (
    <div className="payment-plan-page" style={{ maxWidth: 600, margin: '2rem auto', padding: '2rem', background: '#fff', borderRadius: 8, boxShadow: '0 2px 8px #eee' }}>
      <h2>Payment Plan</h2>
      <div><strong>Change ID:</strong> {paymentPlan.changeId}</div>
      <div><strong>Plan de Calcul ID:</strong> {paymentPlan.planDeCalculId}</div>
      <div><strong>Payment Plan ID:</strong> {paymentPlan.paymentPlanId}</div>
      <div><strong>Type:</strong> {paymentPlan.isAutoGenerated ? 'Auto-generated' : 'Manual'}</div>
      <table style={{ width: '100%', marginTop: '1rem', borderCollapse: 'collapse' }}>
        <thead>
          <tr style={{ background: '#f5f5f5' }}>
            <th style={{ padding: '0.5rem', border: '1px solid #ddd' }}>Month</th>
            <th style={{ padding: '0.5rem', border: '1px solid #ddd' }}>Amount</th>
          </tr>
        </thead>
        <tbody>
          {paymentPlan.payments.map(({ month, amount }) => (
            <tr key={month}>
              <td style={{ padding: '0.5rem', border: '1px solid #ddd' }}>{month}</td>
              <td style={{ padding: '0.5rem', border: '1px solid #ddd' }}>{amount}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
