// paymentPlanAutomation.js
// Pure automation function for payment plan creation
import { hasPaymentPlan } from './paymentPlanProjection';
import { createPaymentPlanAutoGeneratedEvent } from './paymentPlanEvents';

/**
 * Automation function: checks if a payment plan should be created and returns new events if needed.
 * - eventLog: array of workflow events
 * Returns: array of new events to append (or empty array)
 */

export function automatePaymentPlanCreation(eventLog) {
  // Find all validated decisions (step 6)
  const validatedDecisions = eventLog.filter(e => e.event === 'DecisionValidee');
  const newEvents = [];

  for (const validatedDecision of validatedDecisions) {
    // Always create a new payment plan for each DecisionValidee
    // Check if a payment plan already exists for this decisionId (not just changeId)
    const alreadyExists = eventLog.some(e =>
      (e.event === 'PaymentPlanCreated' || e.event === 'PaymentPlanAutoGenerated') &&
      e.decisionId === validatedDecision.decisionId
    );
    if (alreadyExists) continue;


    // Extract month and toPayOrReimburse from DecisionValidee payload
    let payments = [];
    if (validatedDecision.payload && Array.isArray(validatedDecision.payload)) {
      payments = validatedDecision.payload.map(p => ({ month: p.month, amount: p.toPayOrReimburse }));
    }

    // Create auto-generated payment plan event, include decisionId
    // Always generate a new paymentPlanId if missing
    let paymentPlanId = validatedDecision.paymentPlanId;
    if (!paymentPlanId) {
      // Use uuidv4 for new paymentPlanId
      if (typeof window !== 'undefined' && window.crypto && window.crypto.randomUUID) {
        paymentPlanId = window.crypto.randomUUID();
      } else {
        // Fallback for Node.js or environments without crypto.randomUUID
        paymentPlanId = require('uuid').v4();
      }
    }
    const paymentPlanEvent = createPaymentPlanAutoGeneratedEvent({
      changeId: validatedDecision.changeId,
      planDeCalculId: validatedDecision.planDeCalculId,
      paymentPlanId,
      decisionId: validatedDecision.decisionId,
      payments,
    });

    // Open step 7 before appending payment plan event
    const workflowId = validatedDecision.workflowId;
    const stepOpenedEvent = {
      event: 'StepOpened',
      workflowId,
      step: 7,
      ts: new Date().toISOString(),
    };
    // Append StepOpened first, then payment plan event
    newEvents.push(stepOpenedEvent, paymentPlanEvent);
  }

  return newEvents;
}
