// paymentPlanProjection.js
// Pure projection functions for payment plan state
import { PAYMENT_PLAN_CREATED, PAYMENT_PLAN_AUTO_GENERATED } from './paymentPlanEvents';
import { getLatestValidatedDecision } from '../valideDecision/valideDecisionProjection';

/**
 * Computes the current payment plan state from the event log.
 * Returns: {
 *   paymentPlanId,
 *   changeId,
 *   planDeCalculId,
 *   payments: Array<{ month, amount }>,
 *   isAutoGenerated: boolean
 * }
 */

export function getPaymentPlanStates(eventLog) {
  // Returns all payment plans, including decisionId
  return eventLog
    .filter(e => e.event === PAYMENT_PLAN_CREATED || e.event === PAYMENT_PLAN_AUTO_GENERATED)
    .map(e => ({
      paymentPlanId: e.paymentPlanId,
      changeId: e.changeId,
      planDeCalculId: e.planDeCalculId,
      decisionId: e.decisionId,
      payments: e.payments || [],
      isAutoGenerated: e.event === PAYMENT_PLAN_AUTO_GENERATED,
      ts: e.ts,
    }));
}

// For backward compatibility, return the latest payment plan

export function getPaymentPlanState(eventLog) {
  // Use latest validated decision for payments
  const latestDecision = getLatestValidatedDecision(eventLog);
  if (!latestDecision) return null;
  const payments = (latestDecision.payload && Array.isArray(latestDecision.payload.payments))
    ? latestDecision.payload.payments.map(p => ({ month: p.month, amount: p.amount }))
    : Object.entries((latestDecision.payload && latestDecision.payload.deltaPerMonth) || {}).map(([month, amount]) => ({ month, amount }));

  return {
    paymentPlanId: latestDecision.paymentPlanId,
    changeId: latestDecision.changeId,
    planDeCalculId: latestDecision.planDeCalculId,
    decisionId: latestDecision.decisionId,
    payments,
    isAutoGenerated: true,
    ts: latestDecision.ts,
  };
}

/**
 * Returns true if a payment plan exists for the given changeId.
 */
export function hasPaymentPlan(eventLog, changeId) {
  return eventLog.some(e =>
    (e.event === PAYMENT_PLAN_CREATED || e.event === PAYMENT_PLAN_AUTO_GENERATED) &&
    e.changeId === changeId
  );
}
